import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { seasons, animals } from '@/lib/db/schema/animals';
import { tasks } from '@/lib/db/schema/tasks';
import { auth } from '@/lib/auth/config';
import { eq, and, desc } from 'drizzle-orm';
import { z } from 'zod';
import { createId } from '@paralleldrive/cuid2';
import { addDays, format as formatDate, differenceInDays, parseISO } from 'date-fns';

// ============================================================================
// VALIDATION SCHEMAS
// ============================================================================

const createSeasonSchema = z.object({
  startDate: z.string(), // ISO date string
  endDate: z.string().optional().nullable(),
  status: z.enum(['active', 'completed']).optional().default('active'),
  durationDays: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  createReminder: z.boolean().optional().default(true),
});

const updateSeasonSchema = createSeasonSchema.partial();

// Helper function to calculate duration
function calculateDuration(startDate: string, endDate?: string): number | null {
  if (!endDate) return null;
  const start = new Date(startDate);
  const end = new Date(endDate);
  const diffTime = Math.abs(end.getTime() - start.getTime());
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays;
}

// ============================================================================
// GET /api/animals/[id]/seasons
// ============================================================================
// Get all seasons for an animal

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: request.headers });
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: animalId } = await params;

    // Verify animal ownership
    const [animal] = await db
      .select()
      .from(animals)
      .where(and(eq(animals.id, animalId), eq(animals.userId, session.user.id)))
      .limit(1);

    if (!animal) {
      return NextResponse.json({ error: 'Animal not found' }, { status: 404 });
    }

    // Verify animal is female
    if (animal.sex !== 'female') {
      return NextResponse.json(
        { error: 'Seasons are only available for female animals' },
        { status: 400 }
      );
    }

    // Get seasons
    const animalSeasons = await db
      .select()
      .from(seasons)
      .where(eq(seasons.animalId, animalId))
      .orderBy(desc(seasons.startDate));

    return NextResponse.json({
      success: true,
      seasons: animalSeasons,
      count: animalSeasons.length,
    });
  } catch (error) {
    console.error('Error fetching seasons:', error);
    return NextResponse.json(
      { error: 'Failed to fetch seasons' },
      { status: 500 }
    );
  }
}

// ============================================================================
// POST /api/animals/[id]/seasons
// ============================================================================
// Create a new season

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: request.headers });
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: animalId } = await params;
    const body = await request.json();

    console.log('📝 Season creation request:', { animalId, body });

    // Validate request body
    const validation = createSeasonSchema.safeParse(body);
    if (!validation.success) {
      console.error('❌ Validation failed:', validation.error.issues);
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: validation.error.issues.map((err) => ({
            field: err.path.join('.'),
            message: err.message,
          })),
        },
        { status: 400 }
      );
    }

    // Verify animal ownership
    const [animal] = await db
      .select()
      .from(animals)
      .where(and(eq(animals.id, animalId), eq(animals.userId, session.user.id)))
      .limit(1);

    if (!animal) {
      return NextResponse.json({ error: 'Animal not found' }, { status: 404 });
    }

    // Verify animal is female
    if (animal.sex !== 'female') {
      return NextResponse.json(
        { error: 'Seasons are only available for female animals' },
        { status: 400 }
      );
    }

    const validatedData = validation.data;

    // Calculate duration if end date provided
    const durationDays = validatedData.endDate
      ? calculateDuration(validatedData.startDate, validatedData.endDate)
      : null;

    // Create season
    const [season] = await db
      .insert(seasons)
      .values({
        // id is auto-generated by database (uuid defaultRandom)
        animalId,
        startDate: validatedData.startDate,
        endDate: validatedData.endDate || null,
        status: validatedData.status || 'active',
        durationDays: validatedData.durationDays || durationDays,
        hasProgesteroneReadings: false,
        progesteroneReadingCount: 0,
        notes: validatedData.notes || null,
      })
      .returning();

    // Create reminder for next predicted season if requested
    let reminderCreated = false;
    if (validatedData.createReminder) {
      try {
        // Get all previous seasons to calculate average cycle length
        const previousSeasons = await db
          .select()
          .from(seasons)
          .where(and(
            eq(seasons.animalId, animalId),
            eq(seasons.status, 'completed')
          ))
          .orderBy(desc(seasons.startDate))
          .limit(5);

        // Calculate average cycle length if we have at least 2 seasons
        if (previousSeasons.length >= 1) {
          const intervals: number[] = [];
          for (let i = 0; i < previousSeasons.length - 1; i++) {
            const current = parseISO(previousSeasons[i].startDate);
            const next = parseISO(previousSeasons[i + 1].startDate);
            intervals.push(differenceInDays(current, next));
          }

          // Use average or default to 21 days (typical cycle)
          const avgInterval = intervals.length > 0
            ? Math.round(intervals.reduce((a, b) => a + b, 0) / intervals.length)
            : 21;

          // Predict next season date
          const lastStartDate = parseISO(validatedData.startDate);
          const predictedNextDate = addDays(lastStartDate, avgInterval);
          
          // Create reminder 7 days before predicted date
          const reminderDate = addDays(predictedNextDate, -7);

          // Only create reminder if it's in the future
          if (reminderDate > new Date()) {
            await db.insert(tasks).values({
              userId: session.user.id,
              animalId: animalId,
              type: 'event',
              title: `${animal.name} - Upcoming Heat Cycle`,
              description: `${animal.name} may be coming into season soon (predicted: ${formatDate(predictedNextDate, 'MMM dd, yyyy')}). Keep an eye out for early signs like behavioral changes, swelling, or spotting. Consider scheduling progesterone testing if planning to breed.`,
              dueDate: formatDate(reminderDate, 'yyyy-MM-dd'),
              priority: 'medium',
              status: 'pending',
            });
            reminderCreated = true;
          }
        }
      } catch (error) {
        console.error('Error creating reminder:', error);
        // Don't fail the whole request if reminder creation fails
      }
    }

    return NextResponse.json({
      success: true,
      data: season,
      reminderCreated,
      message: reminderCreated 
        ? 'Season created and reminder set for next predicted cycle'
        : 'Season created successfully',
    });
  } catch (error) {
    console.error('Error creating season:', error);
    return NextResponse.json(
      { error: 'Failed to create season' },
      { status: 500 }
    );
  }
}
