import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { feedingPlans, animals } from '@/lib/db/schema/animals';
import { tasks } from '@/lib/db/schema/tasks';
import { auth } from '@/lib/auth/config';
import { eq, and, desc } from 'drizzle-orm';
import { z } from 'zod';
import { format } from 'date-fns';
import { createNotification } from '@/lib/services/notification-creator';

// ============================================================================
// VALIDATION SCHEMAS
// ============================================================================

const mealTimeSchema = z.object({
  time: z.string(), // "08:00"
  amount: z.string(), // "2 cups"
  unit: z.string(), // "cups", "grams", etc.
});

const supplementSchema = z.object({
  name: z.string(),
  dosage: z.string(),
  frequency: z.string(),
});

const createFeedingPlanSchema = z.object({
  foodType: z.string().optional(),
  mealTimes: z.array(mealTimeSchema).optional(),
  specialDiet: z.string().optional(),
  supplements: z.array(supplementSchema).optional(),
  calorieTarget: z.number().int().positive().optional(),
  specialNotes: z.string().optional(),
  isActive: z.boolean().optional().default(true),
  createTasks: z.boolean().optional().default(false), // Create tasks for today
});

const updateFeedingPlanSchema = createFeedingPlanSchema.partial();

// ============================================================================
// GET /api/animals/[id]/feeding-plans
// ============================================================================
// Get all feeding plans for an animal

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: request.headers });
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: animalId } = await params;

    // Verify animal ownership
    const [animal] = await db
      .select()
      .from(animals)
      .where(and(eq(animals.id, animalId), eq(animals.userId, session.user.id)))
      .limit(1);

    if (!animal) {
      return NextResponse.json({ error: 'Animal not found' }, { status: 404 });
    }

    // Get feeding plans
    const plans = await db
      .select()
      .from(feedingPlans)
      .where(eq(feedingPlans.animalId, animalId))
      .orderBy(desc(feedingPlans.createdAt));

    return NextResponse.json({
      success: true,
      data: plans,
    });
  } catch (error) {
    console.error('Error fetching feeding plans:', error);
    return NextResponse.json(
      { error: 'Failed to fetch feeding plans' },
      { status: 500 }
    );
  }
}

// ============================================================================
// POST /api/animals/[id]/feeding-plans
// ============================================================================
// Create a new feeding plan

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: request.headers });
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: animalId } = await params;
    const body = await request.json();

    console.log('📝 Feeding plan creation request:', { animalId, body });

    // Validate request body
    const validation = createFeedingPlanSchema.safeParse(body);
    if (!validation.success) {
      console.error('❌ Validation failed:', validation.error.issues);
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: validation.error.issues.map((err) => ({
            field: err.path.join('.'),
            message: err.message,
          })),
        },
        { status: 400 }
      );
    }

    // Verify animal ownership
    const [animal] = await db
      .select()
      .from(animals)
      .where(and(eq(animals.id, animalId), eq(animals.userId, session.user.id)))
      .limit(1);

    if (!animal) {
      console.error('❌ Animal not found:', animalId);
      return NextResponse.json({ error: 'Animal not found' }, { status: 404 });
    }

    console.log('🐕 Animal found:', { id: animal.id, name: animal.name });

    const validatedData = validation.data;

    // If this plan is active, deactivate other plans
    if (validatedData.isActive) {
      await db
        .update(feedingPlans)
        .set({ isActive: false, updatedAt: new Date() })
        .where(
          and(
            eq(feedingPlans.animalId, animalId),
            eq(feedingPlans.isActive, true)
          )
        );
    }

    // Create feeding plan (id is auto-generated by database)
    const [plan] = await db
      .insert(feedingPlans)
      .values({
        animalId,
        foodType: validatedData.foodType || null,
        mealTimes: validatedData.mealTimes as any || null,
        specialDiet: validatedData.specialDiet || null,
        supplements: validatedData.supplements as any || null,
        calorieTarget: validatedData.calorieTarget || null,
        specialNotes: validatedData.specialNotes || null,
        isActive: validatedData.isActive ?? true,
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      .returning();

    // Create feeding tasks for today if requested
    let tasksCreated = 0;
    if (validatedData.createTasks && validatedData.mealTimes && validatedData.mealTimes.length > 0) {
      const today = format(new Date(), 'yyyy-MM-dd');
      
      for (const meal of validatedData.mealTimes) {
        try {
          // Create task (id is auto-generated by database)
          const [task] = await db.insert(tasks).values({
            userId: session.user.id,
            animalId,
            type: 'feeding',
            title: `Feed ${animal.name}`,
            description: `${meal.amount} ${meal.unit} of ${validatedData.foodType || 'food'}`,
            dueDate: today,
            dueTime: meal.time,
            status: 'pending',
            priority: 'medium',
            taskData: {
              foodType: validatedData.foodType,
              amount: parseFloat(meal.amount) || 0,
              unit: meal.unit,
            },
            createdAt: new Date(),
            updatedAt: new Date(),
          }).returning();
          
          tasksCreated++;

          // Create notification for the feeding task
          if (task) {
            try {
              await createNotification({
                userId: session.user.id,
                type: 'event_reminder',
                title: `🍽️ Feeding Reminder: ${animal.name}`,
                message: `Don't forget to feed ${animal.name} at ${meal.time} - ${meal.amount} ${meal.unit} of ${validatedData.foodType || 'food'}`,
                actionUrl: '/tasks',
                actionLabel: 'View Tasks',
                relatedEntityType: 'task',
                relatedEntityId: task.id,
                metadata: {
                  taskType: 'feeding',
                  animalId,
                  animalName: animal.name,
                  mealTime: meal.time,
                  amount: `${meal.amount} ${meal.unit}`,
                  foodType: validatedData.foodType,
                },
              });
            } catch (notifError) {
              console.error('Failed to create notification for feeding task:', notifError);
              // Don't fail the task creation if notification fails
            }
          }
        } catch (taskError) {
          console.error('Failed to create feeding task:', taskError);
          // Continue creating other tasks even if one fails
        }
      }
    }

    console.log(`✅ Feeding plan created successfully. Tasks created: ${tasksCreated}`);

    return NextResponse.json({
      success: true,
      data: plan,
      tasksCreated,
      message: tasksCreated > 0 
        ? `Feeding plan created with ${tasksCreated} task(s)`
        : 'Feeding plan created successfully',
    });
  } catch (error) {
    console.error('Error creating feeding plan:', error);
    return NextResponse.json(
      { error: 'Failed to create feeding plan' },
      { status: 500 }
    );
  }
}
