import { pgTable, text, timestamp, boolean, integer, pgEnum, date, uuid, decimal, jsonb } from 'drizzle-orm/pg-core';
import { animals } from './animals';
import { users } from './users';

// ============================================================================
// ENUMS
// ============================================================================

export const taskTypeEnum = pgEnum('task_type', [
  'feeding',
  'exercise',
  'grooming',
  'weight',
  'cleaning',
  'event',
  'puppy_feeding', // Auto-generated feeding tasks
  'misc'
]);

export const eventTypeEnum = pgEnum('event_type', [
  'vet_visit',
  'vaccination',
  'worming',
  'heartworm',
  'flea_tick',
  'rugging',
  'pest_management',
  'pregnancy_ultrasound',      // Ultrasound screening (21-28 days post-mating)
  'pregnancy_blood_test',      // Blood test for relaxin (25-30 days)
  'pregnancy_xray',            // X-ray for puppy count (45+ days)
  'pregnancy_checkup',         // General pregnancy vet checkup
  'other'
]);

export const taskStatusEnum = pgEnum('task_status', [
  'pending',
  'completed',
  'skipped',
  'overdue'
]);

export const taskPriorityEnum = pgEnum('task_priority', [
  'low',
  'medium',
  'high'
]);

// ============================================================================
// MAIN TASKS TABLE
// ============================================================================

export const tasks = pgTable('tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  animalId: uuid('animal_id').references(() => animals.id, { onDelete: 'cascade' }), // Optional for general tasks

  type: taskTypeEnum('type').notNull(),
  title: text('title').notNull(),
  description: text('description'),

  // Scheduling
  dueDate: date('due_date'),
  dueTime: text('due_time'), // HH:MM format
  status: taskStatusEnum('status').default('pending'),
  priority: taskPriorityEnum('priority').default('medium'), // ⭐ NEW

  // Completion tracking
  completedAt: timestamp('completed_at'),
  completedBy: text('completed_by').references(() => users.id),

  // Task-specific data (JSONB for flexibility)
  taskData: jsonb('task_data').$type<{
    // Feeding
    foodType?: string;
    amount?: number;
    unit?: string; // grams, cups, etc.

    // Exercise
    exerciseType?: string; // walk, play, training
    duration?: number; // minutes

    // Grooming
    groomingType?: string; // bath, brush, nails, ears, teeth

    // Weight
    weight?: number; // kg
    weightUnit?: string;

    // Cleaning
    area?: string; // kennel, whelping area, etc.
    cleaningType?: string;
    frequency?: string;

    // Event
    eventType?: string;
    location?: string;
    time?: string;
    isRecurring?: boolean;

    // Progesterone Test (Auto-generated) ⭐ NEW
    progesteroneTestData?: {
      heatCycleId: string;
      cycleDay: number;
      previousLevel?: number;
      autoGenerated: boolean;
    };

    // Pregnancy Screening (Auto-generated) ⭐ NEW
    pregnancyScreeningData?: {
      heatCycleId: string;
      breedingRecordId: string;
      lastMatingDate: string; // ISO date string
      daysPostMating: number; // Days since last mating
      screeningType: 'ultrasound' | 'blood_test' | 'xray' | 'checkup';
      autoGenerated: boolean;
      generatedDate: string;
    };

    // Puppy Feeding (Auto-generated) ⭐ NEW
    puppyFeedingData?: {
      litterId: string;
      puppyId: string;
      puppyName: string;
      puppyAge: string; // "3-4 months" or "4-6 months"
      feedingsPerDay: number; // 2 or 3
      autoGenerated: boolean;
      generatedDate: string;
    };

    // Misc
    notes?: string;
  }>(),

  // Recurring task settings
  isRecurring: boolean('is_recurring').default(false),
  recurringPattern: text('recurring_pattern'), // daily, weekly, monthly
  recurringInterval: integer('recurring_interval'), // Every X days/weeks/months
  recurringUntil: date('recurring_until'),

  // Auto-generation tracking ⭐ NEW
  isAutoGenerated: boolean('is_auto_generated').default(false),
  generatedBy: text('generated_by'), // 'puppy_feeding_generator', 'system', etc.
  generationBatchId: text('generation_batch_id'), // Group auto-generated tasks

  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// ============================================================================
// TASK REMINDERS
// ============================================================================

export const taskReminders = pgTable('task_reminders', {
  id: uuid('id').primaryKey().defaultRandom(),
  taskId: uuid('task_id').references(() => tasks.id, { onDelete: 'cascade' }).notNull(),
  userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),

  reminderTime: timestamp('reminder_time').notNull(),
  reminderType: text('reminder_type'), // email, push, sms

  sent: boolean('sent').default(false),
  sentAt: timestamp('sent_at'),
  error: text('error'), // If sending failed

  createdAt: timestamp('created_at').defaultNow(),
});

// ============================================================================
// WEIGHT TRACKING (HISTORICAL DATA)
// ============================================================================

export const weightRecords = pgTable('weight_records', {
  id: uuid('id').primaryKey().defaultRandom(),
  animalId: uuid('animal_id').references(() => animals.id, { onDelete: 'cascade' }).notNull(),
  userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),

  weight: decimal('weight', { precision: 5, scale: 2 }).notNull(), // kg
  unit: text('unit').default('kg'),

  recordedDate: date('recorded_date').notNull(),
  recordedTime: text('recorded_time'), // HH:MM format

  // Context
  recordingMethod: text('recording_method'), // manual, task_completion, vet_visit
  taskId: uuid('task_id').references(() => tasks.id), // If from weight task

  // Metadata
  notes: text('notes'),
  bodyConditionScore: integer('body_condition_score'), // 1-9 scale
  isIdealWeight: boolean('is_ideal_weight'),

  createdAt: timestamp('created_at').defaultNow(),
});

// ============================================================================
// PUPPY FEEDING GENERATION HISTORY ⭐ NEW
// ============================================================================

export const puppyFeedingGenerations = pgTable('puppy_feeding_generations', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),

  generatedAt: timestamp('generated_at').defaultNow(),
  batchId: text('batch_id').notNull(), // Groups tasks generated together

  // Generation parameters
  startDate: date('start_date').notNull(),
  endDate: date('end_date').notNull(), // Usually 7 days from start
  daysGenerated: integer('days_generated'), // 7

  // Summary
  littersProcessed: integer('litters_processed'),
  puppiesProcessed: integer('puppies_processed'),
  tasksGenerated: integer('tasks_generated'),

  // Detailed breakdown
  generationData: jsonb('generation_data').$type<{
    litters: Array<{
      litterId: string;
      sireName: string;
      puppyCount: number;
      ageCategory: string; // "3-4 months" or "4-6 months"
      feedingsPerDay: number;
      tasksCreated: number;
    }>;
  }>(),

  notes: text('notes'),
});

// ============================================================================
// TYPE EXPORTS FOR DRIZZLE INFERENCE
// ============================================================================

export type Task = typeof tasks.$inferSelect;
export type NewTask = typeof tasks.$inferInsert;

export type TaskReminder = typeof taskReminders.$inferSelect;
export type NewTaskReminder = typeof taskReminders.$inferInsert;

export type WeightRecord = typeof weightRecords.$inferSelect;
export type NewWeightRecord = typeof weightRecords.$inferInsert;

export type PuppyFeedingGeneration = typeof puppyFeedingGenerations.$inferSelect;
export type NewPuppyFeedingGeneration = typeof puppyFeedingGenerations.$inferInsert;

// ============================================================================
// TYPESCRIPT INTERFACES FOR TASK DATA
// ============================================================================

export interface FeedingTaskData {
  foodType?: string;
  amount?: number;
  unit?: string;
}

export interface ExerciseTaskData {
  exerciseType?: string;
  duration?: number;
}

export interface GroomingTaskData {
  groomingType?: string;
}

export interface WeightTaskData {
  weight?: number;
  unit?: string;
}

export interface CleaningTaskData {
  area?: string;
  cleaningType?: string;
  frequency?: string;
}

export interface EventTaskData {
  eventType?: string;
  location?: string;
  time?: string;
}

export interface PuppyFeedingTaskData {
  litterId: string;
  puppyId: string;
  puppyName: string;
  puppyAge: string;
  feedingsPerDay: number;
  autoGenerated: boolean;
  generatedDate: string;
}

export interface MiscTaskData {
  notes?: string;
}

// Union type for all task data
export type TaskData = {
  foodType?: string;
  amount?: number;
  unit?: string;
  exerciseType?: string;
  duration?: number;
  groomingType?: string;
  weight?: number;
  area?: string;
  cleaningType?: string;
  frequency?: string;
  eventType?: string;
  location?: string;
  time?: string;
  puppyFeedingData?: PuppyFeedingTaskData;
  notes?: string;
};
